version: "3.9"

services:
  rainbow-bridge:
    image: ghcr.io/yi-nology/rainbow_bridge:latest
    container_name: rainbow-bridge
    restart: unless-stopped
    command:
      - "--config"
      - "/etc/rainbow_bridge/config.yaml"
    environment:
      TZ: Asia/Shanghai
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/etc/rainbow_bridge/config.yaml:ro
      - rainbow_bridge_data:/var/lib/rainbow_bridge

volumes:
  rainbow_bridge_data:
    driver: local
